name: ci-nx

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npx nx-cloud start-ci-run \
          --distribute-on="3 linux-medium-js" \
          --stop-agents-after="e2e-ci"
     
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - run: npm ci --frozen-lockfile

      # Nx lint all projects
      - run: npx nx run-many --target=lint --all=true --parallel=3

       # Nx run e2e-ci target on all projects 
       # - run: npx nx run-many --target=e2e-ci --projects=app1-e2e --parallel=1
      


        