name: ci-nx-affected

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Install Playwright Browsers
        run: PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers npx playwright install --with-deps

      - uses: nrwl/nx-set-shas@v4

      - run: git branch --track master origin/master

      # - name: Lint affected projects
      #   run: npx nx affected -t lint

      - name: Run affected e2e tests
        run: npx nx affected -t e2e-ci
    
