name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
     matrix:
        shardIndex: [1]
        shardTotal: [1]

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      - run: npx nx-cloud record -- nx format:check

      # Nx Affected runs only tasks affected by the changes in this commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t lint test build e2e-ci --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

        